name: mcp_http_tool
description: A MCP HTTP mode for OpenTool, allowing OpenTool call to operator MCP HTTP.
version: 1.0.0
repository: https://github.com/opentool-hub/opentool-server-mcp-http

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  args: ^2.5.0
  json_annotation: ^4.9.0
  mcp_dart: ^0.5.3
  opentool_dart:
    path: ../opentool-dart

dev_dependencies:
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
